"""Add timestamp to FriendRequest

Revision ID: c60439923ebd
Revises: 046648c9db94
Create Date: 2025-12-04 17:56:03.429561

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c60439923ebd'
down_revision = '046648c9db94'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('friend_request', schema=None) as batch_op:
        batch_op.add_column(sa.Column('timestamp', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('friend_request', schema=None) as batch_op:
        batch_op.drop_column('timestamp')

    # ### end Alembic commands ###
